project:
  type: website
  output-dir: _analysis_website

format:
  html:
    theme: simplex
    toc: true
    page-layout: full

website:
  title: "GPFA Imputation Analysis"
  site-url: "https://mone27.github.io/gpfa_imputation"
  description: "Time series imputation using Gaussian Processes Factor Analsysis (GPFA)"
  repo-branch: master
  repo-url: "https://github.com/mone27/gpfa_imputation/"
  twitter-card: true
  open-graph: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Library Docs"
        file: "lib"
  # sidebar:
  #   style: floating
  #   contents: auto
