project:
  type: website
  output-dir: _analysis_website

format:
  html:
    theme: simplex
    toc: true
    page-layout: full

website:
  title: "Meteo Imputation"
  site-url: "https://mone27.github.io/meteo_imp"
  description: "Meteo Imputation"
  repo-branch: master
  repo-url: "https://github.com/mone27/metep_imp/"
  twitter-card: true
  open-graph: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Library Docs"
        file: "lib"
  # sidebar:
  #   style: floating
  #   contents: auto
